# buyer-app/transaction_handler.py
import json
import time
from PIL import Image
from pyzbar.pyzbar import decode
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives import serialization

# --- Buyer's Wallet and Keys ---
# In a real app, keys would be stored securely in the device's keystore.
# For this demo, we generate them on the fly.

# Generate a private/public key pair for the buyer for digital signatures
private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
public_key = private_key.public_key()

# Serialize public key to share it (e.g., with the bank)
pem_public_key = public_key.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo
)

BUYER_DATA = {
    "id": "BUYER_67890",
    "name": "John Doe",
    "public_key": pem_public_key.decode('utf-8')
}

def read_qr_code(file_path="payment_qr.png"):
    """
    Reads a QR code image and returns the decoded data.
    """
    try:
        image = Image.open(file_path)
        decoded_objects = decode(image)
        if not decoded_objects:
            print("No QR code found in the image.")
            return None

        qr_data = decoded_objects[0].data.decode("utf-8")
        print("Successfully read QR code.")
        return json.loads(qr_data)
    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
        return None
    except Exception as e:
        print(f"An error occurred while reading the QR code: {e}")
        return None

def process_payment_request(transaction_data):
    """
    Processes the payment request and generates a signed digital receipt.
    """
    if not transaction_data or transaction_data.get("type") != "PAYMENT_REQUEST":
        raise ValueError("Invalid or missing payment request data.")

    # In a real app, you would confirm this with the user.
    print("\n--- Payment Details ---")
    print(f"Seller: {transaction_data['seller_info']['name']}")
    print(f"Amount: {transaction_data['transaction_details']['amount']} {transaction_data['transaction_details']['currency']}")
    print("-----------------------")
    user_confirmation = input("Do you approve this payment? (yes/no): ").lower()

    if user_confirmation != 'yes':
        print("Payment cancelled.")
        return None

    # --- Create a Digital Receipt ---
    # The receipt includes buyer info and references the original transaction.
    receipt = {
        "type": "PAYMENT_CONFIRMATION",
        "buyer_info": {
            "id": BUYER_DATA["id"],
            "name": BUYER_DATA["name"],
            "public_key": BUYER_DATA["public_key"]
        },
        "original_transaction_id": transaction_data["transaction_details"]["transaction_id"],
        "status": "CONFIRMED",
        "timestamp": int(time.time())
    }

    # --- Sign the Receipt ---
    # The signature proves the buyer authorized this transaction.
    message_to_sign = json.dumps(receipt, sort_keys=True).encode('utf-8')
    signature = private_key.sign(
        message_to_sign,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    # Attach the signature to the final confirmation data
    confirmation_data = {
        "receipt": receipt,
        "signature": signature.hex()  # Convert signature to hex for easy transport
    }

    print("\nPayment successful! Digital receipt created and signed.")
    return confirmation_data

if __name__ == '__main__':
    # --- Demo: Buyer scans QR and processes payment ---

    # 1. Read the QR code generated by the seller
    payment_data = read_qr_code() # Assumes 'payment_qr.png' is in the root

    if payment_data:
        # 2. Process the payment request
        # This function will ask for user confirmation.
        signed_confirmation = process_payment_request(payment_data)

        if signed_confirmation:
            print("\n--- Signed Confirmation Data (to be shown to seller) ---")
            print(json.dumps(signed_confirmation, indent=4))
